export const attributeDescriptions: Record<string, string> = {
  pace: 'Explosiveness and top speed when running with or without the ball.',
  acceleration: 'How quickly the player reaches top speed from the first steps.',
  ball_control: 'Quality of first touch and control under pressure.',
  dribbling: 'Ability to beat opponents and carry the ball in tight spaces.',
  finishing: 'Quality and consistency of converting chances into goals.',
  long_shots: 'Threat and technique when shooting from outside the box.',
  attacking_movement: 'Intelligence and timing of attacking runs into dangerous areas.',
  heading: 'Effectiveness in aerial attacking and defensive duels.',
  passing: 'Accuracy and reliability of passing to teammates.',
  crossing: 'Accuracy and danger of crosses from wide areas.',
  creativity: 'Vision and ability to create chances others do not see.',
  leadership: 'Ability to organise, inspire and raise the level of teammates.',
  concentration: 'Ability to stay focused and avoid mistakes throughout the match.',
  aggression: 'Competitive edge, intensity and willingness to engage physically.',
  composure: 'Calmness and control in high-pressure moments.',
  work_rate: 'Willingness to keep running, pressing and helping the team off the ball.',
  strength: 'Physical power in duels, shielding and contact situations.',
  agility: 'Sharpness and balance when turning or changing direction.',
  stamina: 'Capacity to sustain intensity over the full match.',
  marking: 'Ability to track opponents and stay tight defensively.',
  tackling: 'Timing and execution of winning the ball cleanly.',
  interceptions: 'Reading passing lanes and cutting out opposition moves.',
  penalties: 'Quality and composure from the penalty spot.',
  free_kicks: 'Technique and threat from direct free kicks.',
  gk_reflexes: 'Shot-stopping reactions in fast close-range situations.',
  gk_one_on_ones: 'Ability to stop attackers in direct one-on-one situations.',
  gk_handling: 'Security and cleanliness when catching or controlling the ball.',
  gk_command_of_area: 'Ability to control the box during crosses and aerial situations.',
  gk_kicking: 'Quality of goalkeeper distribution with the feet.',
  gk_throwing: 'Accuracy and usefulness of goalkeeper throws to start attacks.',
  gk_rushing_out: 'Judgement and effectiveness when leaving the line aggressively.',
  gk_eccentricity: 'Tendency to attempt unusual, risky or adventurous actions.',
};