import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from '../components/TopNav';
import RouteOverlayLoader from '@/components/RouteOverlayLoader';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}>
        <TopNav />
        <RouteOverlayLoader />
        {children}
      </body>
    </html>
  );
}
