version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=eu-central-1
      - AWS_DEFAULT_REGION=eu-central-1
      - VOTES_TABLE_NAME=zcout-votes-dev
      - ACCUMULATORS_TABLE_NAME=zcout-acc-v2-dev
      - RATINGS_TABLE_NAME=zcout-ratings-dev
      - PLAYERS_TABLE_NAME=zcout-players-dev
      - DYNAMODB_ENDPOINT=http://dynamodb:8000


    depends_on:
      - dynamodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://zcout:TwojeSilneHaslo123@host.docker.internal:5433/postgres?sslmode=disable
    depends_on:
      - backend

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./dynamodb-data:/data

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8002:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
