FROM node:20 AS builder

ARG NEXT_PUBLIC_API_BASE
ARG NEXT_PUBLIC_APP_ORIGIN
ARG NEXT_PUBLIC_ENABLE_WS
ARG NEXT_PUBLIC_PUSHER_APP_KEY
ARG NEXT_PUBLIC_PUSHER_HOST
ARG NEXT_PUBLIC_PUSHER_PORT
ARG NEXT_PUBLIC_PUSHER_SCHEME
ARG NEXT_PUBLIC_PUSHER_APP_CLUSTER

ENV NEXT_PUBLIC_API_BASE=$NEXT_PUBLIC_API_BASE
ENV NEXT_PUBLIC_APP_ORIGIN=$NEXT_PUBLIC_APP_ORIGIN
ENV NEXT_PUBLIC_ENABLE_WS=$NEXT_PUBLIC_ENABLE_WS
ENV NEXT_PUBLIC_PUSHER_APP_KEY=$NEXT_PUBLIC_PUSHER_APP_KEY
ENV NEXT_PUBLIC_PUSHER_HOST=$NEXT_PUBLIC_PUSHER_HOST
ENV NEXT_PUBLIC_PUSHER_PORT=$NEXT_PUBLIC_PUSHER_PORT
ENV NEXT_PUBLIC_PUSHER_SCHEME=$NEXT_PUBLIC_PUSHER_SCHEME
ENV NEXT_PUBLIC_PUSHER_APP_CLUSTER=$NEXT_PUBLIC_PUSHER_APP_CLUSTER

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build


FROM node:20-slim

WORKDIR /app

RUN groupadd -r app && useradd -r -g app app

COPY --from=builder /app/package*.json ./

RUN npm ci --omit=dev

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

USER app

EXPOSE 3000

CMD ["npm", "start"]