FROM public.ecr.aws/lambda/python:3.11

COPY app/ app/
COPY main.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

CMD ["main.handler"]

