import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Inter, IBM_Plex_Sans_Condensed } from 'next/font/google';
import './globals.css';
import TopNav from '../components/TopNav';
import RouteOverlayLoader from '@/components/RouteOverlayLoader';

const inter = Inter({ subsets: ['latin'] });

const ratingFont = IBM_Plex_Sans_Condensed({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-rating',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cool-slate">
      <body className={`${inter.className} ${ratingFont.variable}`}>
        <TopNav />
        <Suspense fallback={null}>
          <RouteOverlayLoader />
        </Suspense>
        {children}
      </body>
    </html>
  );
}