import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import TopNav from '../components/TopNav';
import RouteOverlayLoader from '@/components/RouteOverlayLoader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cool-slate">
      <body className={inter.className}>
        <TopNav />
        <Suspense fallback={null}>
          <RouteOverlayLoader />
        </Suspense>
        {children}
      </body>
    </html>
  );
}