import type { Metadata } from 'next';
import { Suspense } from 'react';
import '@fontsource/inter';
import '@fontsource/ibm-plex-sans-condensed/600.css';
import '@fontsource/ibm-plex-sans-condensed/700.css';
import './globals.css';
import TopNav from '../components/TopNav';
import RouteOverlayLoader from '@/components/RouteOverlayLoader';
import AuthProvider from '@/components/AuthProvider';

export const metadata = {
  title: 'Zcout',
  description: 'Zcout',
  icons: {
    icon: '/favicon.png',
  },
}

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cool-slate">
      <body>
        <AuthProvider>
          <TopNav />
          <Suspense fallback={null}>
            <RouteOverlayLoader />
          </Suspense>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}